services:
  xmatches:
    image: xaitan/x-matches:latest
    platform: ${PLATFORM:-linux/arm64}
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
      - DB_PATH=/data/xmatches.db
    volumes:
      - xmatches-data:/data

volumes:
  xmatches-data:
