services:
  # One-time init to fix volume ownership for non-root runtime
  xmatches-init:
    image: busybox:1.36
    command: ["sh","-c","chown -R 65532:65532 /data"]
    volumes:
      - xmatches-data:/data
    restart: "no"

  xmatches:
    image: xaitan/x-matches:latest
    platform: ${PLATFORM:-linux/arm64}
    depends_on:
      xmatches-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
      - DB_PATH=/data/xmatches.db
      # Use non-Secure cookies when serving over plain HTTP locally
      # In production behind HTTPS, remove this line to keep Secure cookies
      - COOKIE_SECURE=false
    volumes:
      - xmatches-data:/data

volumes:
  xmatches-data:
