name: Gosec

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  gosec:
    name: gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download deps
        env:
          GOTOOLCHAIN: local
        run: go mod download

      - name: Install gosec
        env:
          GOTOOLCHAIN: local
        run: go install github.com/securego/gosec/v2/cmd/gosec@v2.21.0

      - name: Run gosec
        env:
          GOTOOLCHAIN: local
        run: $(go env GOPATH)/bin/gosec ./...
